name: 국내 주식 수정주가 크롤링해서 저장하기

on:
  schedule:
    - cron: '0 9 * * 6'

env:
  IS_GITHUB_ACTION: True
  DB_USER: ${{ secrets.DB_USER }}
  DB_PW: ${{ secrets.DB_PW }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB: ${{ secrets.DB }}


jobs:
  run_kor_price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run kor_price.py
        run: python crawling_adjust_stock_price_kor.py